/**
 * Build Tracker Enums
 * Based on the database schema design
 */

export enum UserRole {
  CLIENT = 'CLIENT',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  SITE_SUPERVISOR = 'SITE_SUPERVISOR',
  CONTRACTOR = 'CONTRACTOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PhaseStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
  BLOCKED = 'BLOCKED',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_REVIEW = 'IN_REVIEW',
  COMPLETED = 'COMPLETED',
  BLOCKED = 'BLOCKED',
  CANCELLED = 'CANCELLED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  MOBILE_MONEY = 'MOBILE_MONEY',
  CARD = 'CARD',
  CASH = 'CASH',
  CRYPTO = 'CRYPTO',
}

export enum Currency {
  USD = 'USD',
  ZWL = 'ZWL',
  ZAR = 'ZAR',
  GBP = 'GBP',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  FLOOR_PLAN = 'FLOOR_PLAN',
  DRONE_FOOTAGE = 'DRONE_FOOTAGE',
  THREE_D_RENDER = 'THREE_D_RENDER',
}

export enum IssueType {
  DEFECT = 'DEFECT',
  DELAY = 'DELAY',
  SAFETY = 'SAFETY',
  MATERIAL = 'MATERIAL',
  WEATHER = 'WEATHER',
  OTHER = 'OTHER',
}

export enum IssueSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IssueStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum NotificationType {
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  MILESTONE_REACHED = 'MILESTONE_REACHED',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  ISSUE_REPORTED = 'ISSUE_REPORTED',
  ISSUE_RESOLVED = 'ISSUE_RESOLVED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  WEATHER_ALERT = 'WEATHER_ALERT',
}

export enum DeviceType {
  CAMERA = 'CAMERA',
  SENSOR = 'SENSOR',
  DRONE = 'DRONE',
  SMART_LOCK = 'SMART_LOCK',
  THERMOSTAT = 'THERMOSTAT',
  LIGHTING = 'LIGHTING',
  ALARM = 'ALARM',
}

export enum DeviceStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  ERROR = 'ERROR',
  MAINTENANCE = 'MAINTENANCE',
}

export enum ContractorSpecialty {
  GENERAL = 'GENERAL',
  ELECTRICAL = 'ELECTRICAL',
  PLUMBING = 'PLUMBING',
  HVAC = 'HVAC',
  ROOFING = 'ROOFING',
  FLOORING = 'FLOORING',
  PAINTING = 'PAINTING',
  LANDSCAPING = 'LANDSCAPING',
  MASONRY = 'MASONRY',
  CARPENTRY = 'CARPENTRY',
  SMART_HOME = 'SMART_HOME',
  SOLAR = 'SOLAR',
  SECURITY = 'SECURITY',
}
